/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef UerService_H
#define UerService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "User_types.h"

namespace demos { namespace user {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class UerServiceIf {
 public:
  virtual ~UerServiceIf() {}
  virtual void put(UserServiceResponse& _return, const UserServiceRequest& request) = 0;
  virtual void get(UserServiceResponse& _return, const UserServiceRequest& request) = 0;
};

class UerServiceIfFactory {
 public:
  typedef UerServiceIf Handler;

  virtual ~UerServiceIfFactory() {}

  virtual UerServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(UerServiceIf* /* handler */) = 0;
};

class UerServiceIfSingletonFactory : virtual public UerServiceIfFactory {
 public:
  UerServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<UerServiceIf>& iface) : iface_(iface) {}
  virtual ~UerServiceIfSingletonFactory() {}

  virtual UerServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(UerServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<UerServiceIf> iface_;
};

class UerServiceNull : virtual public UerServiceIf {
 public:
  virtual ~UerServiceNull() {}
  void put(UserServiceResponse& /* _return */, const UserServiceRequest& /* request */) {
    return;
  }
  void get(UserServiceResponse& /* _return */, const UserServiceRequest& /* request */) {
    return;
  }
};

typedef struct _UerService_put_args__isset {
  _UerService_put_args__isset() : request(false) {}
  bool request :1;
} _UerService_put_args__isset;

class UerService_put_args {
 public:

  UerService_put_args(const UerService_put_args&);
  UerService_put_args& operator=(const UerService_put_args&);
  UerService_put_args() {
  }

  virtual ~UerService_put_args() throw();
  UserServiceRequest request;

  _UerService_put_args__isset __isset;

  void __set_request(const UserServiceRequest& val);

  bool operator == (const UerService_put_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const UerService_put_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UerService_put_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class UerService_put_pargs {
 public:


  virtual ~UerService_put_pargs() throw();
  const UserServiceRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UerService_put_result__isset {
  _UerService_put_result__isset() : success(false) {}
  bool success :1;
} _UerService_put_result__isset;

class UerService_put_result {
 public:

  UerService_put_result(const UerService_put_result&);
  UerService_put_result& operator=(const UerService_put_result&);
  UerService_put_result() {
  }

  virtual ~UerService_put_result() throw();
  UserServiceResponse success;

  _UerService_put_result__isset __isset;

  void __set_success(const UserServiceResponse& val);

  bool operator == (const UerService_put_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const UerService_put_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UerService_put_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UerService_put_presult__isset {
  _UerService_put_presult__isset() : success(false) {}
  bool success :1;
} _UerService_put_presult__isset;

class UerService_put_presult {
 public:


  virtual ~UerService_put_presult() throw();
  UserServiceResponse* success;

  _UerService_put_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _UerService_get_args__isset {
  _UerService_get_args__isset() : request(false) {}
  bool request :1;
} _UerService_get_args__isset;

class UerService_get_args {
 public:

  UerService_get_args(const UerService_get_args&);
  UerService_get_args& operator=(const UerService_get_args&);
  UerService_get_args() {
  }

  virtual ~UerService_get_args() throw();
  UserServiceRequest request;

  _UerService_get_args__isset __isset;

  void __set_request(const UserServiceRequest& val);

  bool operator == (const UerService_get_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const UerService_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UerService_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class UerService_get_pargs {
 public:


  virtual ~UerService_get_pargs() throw();
  const UserServiceRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UerService_get_result__isset {
  _UerService_get_result__isset() : success(false) {}
  bool success :1;
} _UerService_get_result__isset;

class UerService_get_result {
 public:

  UerService_get_result(const UerService_get_result&);
  UerService_get_result& operator=(const UerService_get_result&);
  UerService_get_result() {
  }

  virtual ~UerService_get_result() throw();
  UserServiceResponse success;

  _UerService_get_result__isset __isset;

  void __set_success(const UserServiceResponse& val);

  bool operator == (const UerService_get_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const UerService_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UerService_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UerService_get_presult__isset {
  _UerService_get_presult__isset() : success(false) {}
  bool success :1;
} _UerService_get_presult__isset;

class UerService_get_presult {
 public:


  virtual ~UerService_get_presult() throw();
  UserServiceResponse* success;

  _UerService_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class UerServiceClient : virtual public UerServiceIf {
 public:
  UerServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  UerServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(UserServiceResponse& _return, const UserServiceRequest& request);
  void send_put(const UserServiceRequest& request);
  void recv_put(UserServiceResponse& _return);
  void get(UserServiceResponse& _return, const UserServiceRequest& request);
  void send_get(const UserServiceRequest& request);
  void recv_get(UserServiceResponse& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class UerServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<UerServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (UerServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_put(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  UerServiceProcessor(::apache::thrift::stdcxx::shared_ptr<UerServiceIf> iface) :
    iface_(iface) {
    processMap_["put"] = &UerServiceProcessor::process_put;
    processMap_["get"] = &UerServiceProcessor::process_get;
  }

  virtual ~UerServiceProcessor() {}
};

class UerServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  UerServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< UerServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< UerServiceIfFactory > handlerFactory_;
};

class UerServiceMultiface : virtual public UerServiceIf {
 public:
  UerServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<UerServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~UerServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<UerServiceIf> > ifaces_;
  UerServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<UerServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void put(UserServiceResponse& _return, const UserServiceRequest& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->put(_return, request);
    }
    ifaces_[i]->put(_return, request);
    return;
  }

  void get(UserServiceResponse& _return, const UserServiceRequest& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, request);
    }
    ifaces_[i]->get(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class UerServiceConcurrentClient : virtual public UerServiceIf {
 public:
  UerServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  UerServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void put(UserServiceResponse& _return, const UserServiceRequest& request);
  int32_t send_put(const UserServiceRequest& request);
  void recv_put(UserServiceResponse& _return, const int32_t seqid);
  void get(UserServiceResponse& _return, const UserServiceRequest& request);
  int32_t send_get(const UserServiceRequest& request);
  void recv_get(UserServiceResponse& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
