/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef User_CONSTANTS_H
#define User_CONSTANTS_H

#include "User_types.h"

namespace demos { namespace user {

class UserConstants {
 public:
  UserConstants();

};

extern const UserConstants g_User_constants;

}} // namespace

#endif
