/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "shared_constants.h"

namespace shared {

const sharedConstants g_shared_constants;

sharedConstants::sharedConstants() {
}

} // namespace

