/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "echo_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace example {


EchoRequest::~EchoRequest() throw() {
}


void EchoRequest::__set_data(const std::string& val) {
  this->data = val;
__isset.data = true;
}

void EchoRequest::__set_need_by_proxy(const int32_t val) {
  this->need_by_proxy = val;
__isset.need_by_proxy = true;
}
std::ostream& operator<<(std::ostream& out, const EchoRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t EchoRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->data);
          this->__isset.data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->need_by_proxy);
          this->__isset.need_by_proxy = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t EchoRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("EchoRequest");

  if (this->__isset.data) {
    xfer += oprot->writeFieldBegin("data", ::apache::thrift::protocol::T_STRING, 1);
    xfer += oprot->writeString(this->data);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.need_by_proxy) {
    xfer += oprot->writeFieldBegin("need_by_proxy", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(this->need_by_proxy);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(EchoRequest &a, EchoRequest &b) {
  using ::std::swap;
  swap(a.data, b.data);
  swap(a.need_by_proxy, b.need_by_proxy);
  swap(a.__isset, b.__isset);
}

EchoRequest::EchoRequest(const EchoRequest& other0) {
  data = other0.data;
  need_by_proxy = other0.need_by_proxy;
  __isset = other0.__isset;
}
EchoRequest& EchoRequest::operator=(const EchoRequest& other1) {
  data = other1.data;
  need_by_proxy = other1.need_by_proxy;
  __isset = other1.__isset;
  return *this;
}
void EchoRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "EchoRequest(";
  out << "data="; (__isset.data ? (out << to_string(data)) : (out << "<null>"));
  out << ", " << "need_by_proxy="; (__isset.need_by_proxy ? (out << to_string(need_by_proxy)) : (out << "<null>"));
  out << ")";
}


ProxyRequest::~ProxyRequest() throw() {
}


void ProxyRequest::__set_need_by_proxy(const int32_t val) {
  this->need_by_proxy = val;
__isset.need_by_proxy = true;
}
std::ostream& operator<<(std::ostream& out, const ProxyRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ProxyRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->need_by_proxy);
          this->__isset.need_by_proxy = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ProxyRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ProxyRequest");

  if (this->__isset.need_by_proxy) {
    xfer += oprot->writeFieldBegin("need_by_proxy", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(this->need_by_proxy);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ProxyRequest &a, ProxyRequest &b) {
  using ::std::swap;
  swap(a.need_by_proxy, b.need_by_proxy);
  swap(a.__isset, b.__isset);
}

ProxyRequest::ProxyRequest(const ProxyRequest& other2) {
  need_by_proxy = other2.need_by_proxy;
  __isset = other2.__isset;
}
ProxyRequest& ProxyRequest::operator=(const ProxyRequest& other3) {
  need_by_proxy = other3.need_by_proxy;
  __isset = other3.__isset;
  return *this;
}
void ProxyRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ProxyRequest(";
  out << "need_by_proxy="; (__isset.need_by_proxy ? (out << to_string(need_by_proxy)) : (out << "<null>"));
  out << ")";
}


EchoResponse::~EchoResponse() throw() {
}


void EchoResponse::__set_data(const std::string& val) {
  this->data = val;
}
std::ostream& operator<<(std::ostream& out, const EchoResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t EchoResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_data = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->data);
          isset_data = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_data)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t EchoResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("EchoResponse");

  xfer += oprot->writeFieldBegin("data", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->data);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(EchoResponse &a, EchoResponse &b) {
  using ::std::swap;
  swap(a.data, b.data);
}

EchoResponse::EchoResponse(const EchoResponse& other4) {
  data = other4.data;
}
EchoResponse& EchoResponse::operator=(const EchoResponse& other5) {
  data = other5.data;
  return *this;
}
void EchoResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "EchoResponse(";
  out << "data=" << to_string(data);
  out << ")";
}

} // namespace
